openapi: 3.0.3
info:
  title: Sample Users CRUD App
  description: This is a Sample Users CRUD App
  version: 1.0.0
tags:
  - name: Users
    description: Operations related to the management of users

paths:
  /users:
    get:
      tags:
        - Users
      operationId: listUsers
      summary: List all users
      responses:
        200:
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - Users
      operationId: createUser
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Successful request. The user was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request. Some provided parameter is invalid or some required parameter is missing. An explanatory message is returned indicating the nature of the error.
        401:
          description: Unauthorized. Authentication information is missing or token is invalid.
        403:
          description: Forbidden. You don't have permission to perform this action. Access token does not have the required scope.
        500:
          description: Internal server error. Please retry the operation a few moments later.


  /users/{id}:
    get:
      summary: Info for a specific user
      operationId: getUsersById
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful request. User information is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Unauthorized. Authentication information is missing or token is invalid.
        403:
          description: Forbidden. You don't have permission to perform this action. Access token does not have the required scope.
        404:
          description: Not found. No user can be found matching the given identifiers.
        500:
          description: Internal server error. Please retry the operation a few moments later.
    delete:
      operationId: deleteUser
      summary: Remove an existing user
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user to delete
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Successful request (no content). The user was deleted.
        401:
          description: Unauthorized. Authentication information is missing or token is invalid.
        403:
          description: Forbidden. You don't have permission to perform this action. Access token does not have the required scope.
        404:
          description: Not found. No user can be found matching the given identifiers.
        500:
          description: Internal server error. Please retry the operation a few moments later.
    patch:
      tags:
        - Users
      operationId: updateUser
      summary: Updates some info of the user
      parameters:
        - name: id
          in: path
          description: ID of the user to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        204:
          description: Successful request (no content). The user has benn successfully modified.
        401:
          description: Unauthorized. Authentication information is missing or token is invalid.
        403:
          description: Forbidden. You don't have permission to perform this action. Access token does not have the required scope.
        404:
          description: Not found. No user can be found matching the given unique identifier.
        500:
          description: Internal server error. Please retry the operation a few moments later.

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthdate:
          type: string
          format: date

    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
